- source/code/include/scxcorelib/scxnameresolver.h
- source/code/scxcorelib/pal/scxnameresolver.cpp
> Add helper function to easily get the hostname from MachineInfo

- build/Makefile.scxsystemlibtests
- test/code/scxsystemlib/disk/scxlvmutils_test.cpp
@Microsoft/ostc-devs @kapilash @gupta-ak
> Test scxlvmutils_test.cpp is not run during tests; it should be

- source/code/scxsystemlib/networkinterface/networkinterface.cpp
- source/code/scxsystemlib/networkinterface/networkinterfaceenumeration.cpp
Add log entries for enumeration of network provider. This was
needed to identify very slow network enumeration.
It turns out that the slow network provider enumeration was due to:
1) Network speed detection (bind() delay), and
2) MAC network address detection (getkerninfo() delay)
While the problem was ultimately a network configuration issue on a
customer's AIX system, these changes are being committed to allow for
easier detection in the future, should this arise again.
@Microsoft/ostc-devs @johnkord
> Add log entries for enumeration of network provider

- source/code/include/scxcorelib/scxlog.h
- source/code/include/scxcorelib/scxsingleton.h
- source/code/scxcorelib/util/log/scxloghandlefactory.cpp
> Add macros for easy SCXSingleton definitions and allocations

- source/code/include/scxcorelib/scxexception.h
- source/code/include/util/XMLWriter.h
- source/code/scxcorelib/pal/scxdirectoryinfo.cpp
- source/code/scxcorelib/pal/scxthread.cpp
- source/code/scxcorelib/pal/scxthreadpool.cpp
- source/code/scxcorelib/pal/scxuser.cpp
- source/code/scxsystemlib/process/processinstance.cpp
- source/code/util/xml/XElement.cpp
- source/code/util/xml/XMLReader.cpp
- source/code/util/xml/XMLWriter.cpp
- test/code/scxcorelib/pal/scxthread_test.cpp
Changes brought forward from the Configuration Manager 2012R2 release branch to the 2016 improvement branch.
> Changes to the PAL from the Release branch

- source/code/scxcorelib/pal/scxdirectoryinfo.cpp
- source/code/scxsystemlib/process/processinstance.cpp
- source/code/util/xml/XMLReader.cpp
> Fix errors due to newer GCC compiler version (unused variables)

- build/Makefile
- test/code/scxcorelib/pal/scxtime_test.cpp
> Fix issues related to Travis Continuous Integration

- source/code/scxsystemlib/memory/memoryinstance.cpp
> Add trace messages for Solaris Memory Computations

- source/code/include/scxcorelib/scxexception.h
- source/code/scxcorelib/pal/scxnameresolver.cpp
@mabicca @Microsoft/ostc-devs 
https://github.com/Microsoft/OMS-Agent-for-Linux/issues/241
> Give remedial information for ERANGE error on gethostbyname_r

- source/code/scxsystemlib/memory/memoryinstance.cpp
> Fix for ZFS memory computation on Solaris (in non-global zones)

- source/code/scxsystemlib/networkinterface/networkinterface.cpp
> Add hysterical diagnostics to NetworkInterfaceInfo::FindAllUsingKStat

- README.md
> Add basic details on dependency injection for unit testing in PAL

- build/configure
> Add basic Mac OS/X support to configure script

- source/code/include/scxsystemlib/installedsoftwaredepend.h
- source/code/scxsystemlib/software/installedsoftwaredepend.cpp
We were previously using the (not very well documented) RPM API for its cli, which caused us to break on the SLES 12 platform. Using popen to invoke RPM's cli is much more dependable, as we don't need to hope that the headers don't change across platforms (which they do for SLES 12).
> Removed RPM API calls and replaced with more dependable CLI

- source/code/scxsystemlib/disk/statisticallogicaldiskenumeration.cpp
On solaris11, enumeration of FileSystemStatisticalInformation shows incorrect total size in Total instance.
On solaris system this enumeration leads to scanning the /etc/mnttab file. For each valid mounted device it gets the size of the rpool and calculates the total size by adding it. But in case of solaris 11 /etc/mnttab file has logical fs names of fs type zfs created on the same rpool. Due to this size of rpool is counted multiple times. 
We can visualize rpool as a VG. And logical fs(zfs) like lvm on this rpool(VG) which can expand dynamically on demand till the size of the rpool or max available free space on the rpool.
> Enum of FSStatisticalInformation shows wrong total size on solaris11

- source/code/scxsystemlib/memory/memoryinstance.cpp
- test/code/scxsystemlib/memory/memoryinstance_test.cpp
With the linux kernel 3.14+ MemAvailable: is available
in /proc/meminfo provides a better way of getting the
Available Memory instead of calculating it as
MemFree: + Cached: + Buffers:
> Correcting Available Memory Calculation for kernel 3.14+

- installer/InstallBuilder/datafileparser.py
- installer/InstallBuilder/scxutil.py
> Fix Python 3 syntax errors

- source/code/include/scxsystemlib/scxsysteminfo.h
- source/code/scxsystemlib/common/scxsysteminfo.cpp
- source/code/scxsystemlib/networkinterface/networkinterface.cpp
Make VIF enumeration configurable.
> VIF enumeration configurable

- source/code/include/scxcorelib/scxfile.h
- source/code/scxcorelib/pal/scxfile.cpp
Randomize the prefix for temp file creation.
> Fix for synchronization issue in script based monitoring

- source/code/scxsystemlib/disk/diskdepend.cpp
- source/code/scxsystemlib/disk/scxlvmutils.cpp
- source/code/scxsystemlib/disk/statisticalphysicaldiskenumeration.cpp
- source/code/scxsystemlib/os/osinstance.cpp
* policheck fixes
* policheck fixes scxlvmutils.cpp
> Yashkhatri/policheck fixes (#10)
