microsoft/pal

- source/code/scxsystemlib/common/GetLinuxOS.sh
- test/code/scxsystemlib/common/getlinuxos_test.cpp
- test/code/scxsystemlib/common/platforms/rhel_7.0/os-release
- test/code/scxsystemlib/common/platforms/rhel_7.0/redhat-release
Since 2016 TP5 kits can be used in 2012R2, the caption for the
SCX_OperatingSystem class has to be compatible with the 2012R2 MPs.
This change allows the caption to be compatible by fetching the
OSFullName parameter from the /etc/redhat-release file (which is
what older 2012R2 kits did).
@Microsoft/ostc-devs
> Fix problem identifying Red Hat systems properly in SCX_OperatingSystem

- source/code/scxsystemlib/networkinterface/networkinterface.cpp
Network interface stats can be retrieved with a command like:
netstat -v | grep -i elap
On AIX, when enumerating network statistics via omicli like:
omicli ei root/scx SCX_EthernetPortStatistics
then the network statistics were being reset. This was due a a
deliberate ioctl to reset the network stats. While there was a
comment to that effect, there was no explanation as to WHY this
was being done.
Still waiting for testing on this, so this is really just to practice with CodeFlow at this time.
> No longer reset network interface counters on AIX

- source/code/scxsystemlib/disk/diskdepend.cpp
- test/code/scxsystemlib/disk/diskpal_test.cpp
@Microsoft/ostc-devs
This commit fixes Bug [7554508](https://microsoft.visualstudio.com/defaultcollection/WSSC/_workitems?_a=edit&id=7554508&triage=true)
Explanation of fix:
On Ubuntu 16.04 enumerate instances for SCX_DiskDrive was failing.
On debugging the issue I found that certain entries in /etc/mtab file that does not correspond to a physical/logical disk were erroneously considered as physical disks. This was causing the failure.
To fix this I added filesystem fuse.lxcfs (Filesystem for the entry causing the issue) in the File System’s to be ignored list.
I also saw this issue on Ubuntu 14.04 too.
To fix this I added efivarfs in ignored file system’s list. 
mtab entry on Ubuntu 16.04 was:
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0 …
> Fix SCX_DiskDrive enumerate instance on Ubuntu

- source/code/scxsystemlib/disk/diskdepend.cpp
- source/code/scxsystemlib/disk/scxlvmutils.cpp
- test/code/scxsystemlib/disk/scxlvmutils_test.cpp
GetDMSlaves results in an erroneous output if the slave of a dm-device is also a dm-device. In such cases, we must traverse to the slaves till we reach a physical disk.
Two tests are introduced to test this functionality to test positive and negative scenarios.
Also included is a minor fix in diskdepend.cpp, which results in empty name under some rare circumstances.
> Fixing Bug#6362479 - dmSlave traversal

- source/code/scxcorelib/util/stringaid.cpp
- source/code/scxsystemlib/common/scxostypeinfo.cpp
- test/code/scxsystemlib/process/processpal_test.cpp
A couple of changes necessary for compilation on the Power8 system.  These are generic changes that apply to all platforms, though.
Change 1:  When checking to see if a wstringstream operation completed successfully, we need to check the bad() operator, not the return value of the operation.
Change 2:  In scxostypeinfo, there was code that had been #ifdef'd out as ULINUIX.  This needed to be more specific, as the IBM was not ULINUX but also did not want the code.
@jeffaco @niroyb  please review
> Jfawcett power8 compile changes

- test/code/scxcorelib/pal/scxfile_test.cpp
@Microsoft/ostc-devs @OpusDude
> Allow bytes read from /dev/random to be == buffer size

- build/configure
- installer/InstallBuilder/linuxrpm.py
Changes: 
----------
configure : We are calculating the PF_MAJOR and PF_MINOR as this is not a Universal linux, PF_MAJOR will be used in naming the rpm file.
linuxrpm.py: Calculating the name for the rpm file (scx-1.6.3-73.rhel.7.ppc.rpm) so that the PF_MAJOR can be used in the FileName.
@Microsoft/ostc-devs  @jeffaco
> Nirsingh power8 pal

- build/configure
- installer/InstallBuilder/linuxrpm.py
- installer/InstallBuilder/unittests/ib_unittests.py
These builds only run on PPC platform (Power*) hosted by AIX
@Microsoft/ostc-devs 
RedHat PPC builds weren't quite right, BUILD_CONFIGURATION was still referring to ULINUX. Resolved this in configure script, which (I believe) negates one of the changes Nirbhay made to `installer/InstallBuilder/linuxrpm.py`.
> Allow PPC builds to be identified as REDHAT, not ULINUX

- source/code/scxcorelib/pal/scxlibglob.cpp
On SLES12 x86_64, many libraries have both a 32 bit and 64 bit version.  On a 64 bit platform, we should be checking the 64 bit library directories first.
> Changing order of lib detection to be 64 bit first, if 64 bit system

- source/code/include/scxsystemlib/statisticaldiskinstance.h
- source/code/scxsystemlib/disk/statisticaldiskinstance.cpp
- test/code/scxsystemlib/disk/diskpal_test.cpp
pbuild was failing due to mismatch of free disk space in Total instance and free space calculated by adding from individual device instances in mnttab file. In case of solaris we should ignore the free space on each partition on zpool rather use free space on zpool itself. 
pbuild test result:
aix_7.1                 osdev16-aix71-01          Done (12:02)
hp_v3_ia64          osdevia-hpux31-01        Done (26:35)
sun_5.10_sparc    osdevsp-sol10-01          Done (14:20)
sun_5.10_x86       osdev86-sol10-01         Done (13:00)
sun_5.11_sparc    osdevsp-sol11-02          Done (14:23)
sun_5.11_x86       osdev86-sol11-01         Done (13:31)
suse_10_32          osdev-sles10-01            Done (13:20)
suse_10_64          osdev64-sles10-01        Done (11:00)
> Fixing pbuild issue

- build/Makefile.pf.AIX
- source/code/scxsystemlib/networkinterface/networkinterface.cpp
Supporting the new Lancer drivers. While calling NDD_GET_ALL_STATS the customer is getting entcore_ioctl.c error with the new Lancer drivers as the length we were passing to the function was less than expected.
> Support IBM lancer drivers for AIX

- source/code/scxsystemlib/common/scxodm.cpp
Sometimes, omiserver will inherit the ODMDIR environment variable that isn't the system environment variable. This can prevent "odmget" commands from succeeding against certain ODM classes like "CuAt", which do not exist in ODM directories other than /etc/objrepos.  Our use of ODM only uses the "Cu" ODM interfaces so therefore we should always set this variable to /etc/objrepos.
This is AIX specific code, so this change only needs to be tested on AIX platforms. I've tested it with CM, but I've yet to test it with SCXCore (which I don't think this will effect). However, I can't imagine this would affect SCXCore negatively, as we never use any ODM class that isn't a "Cu"
> Set ODMDIR environment variable to be the system ODM (not user).

- source/code/scxsystemlib/common/GetLinuxOS.sh
- test/code/scxsystemlib/common/getlinuxos_test.cpp
Reported via PAL issue #56
@Microsoft/ostc-devs
> Fix typo ("Softare" vs. "Software") in GetLinuxOS.sh and tests.

- source/code/scxsystemlib/disk/diskdepend.cpp
- test/code/scxsystemlib/disk/diskpal_test.cpp
"tracefs" is getting enumerated in disk enumeration as "tracefs" is not part of ignored file system. Due to this following error message keep on logging into scx.log file in each disk enumeration which leads to increase in scx log file size.
**"mount -l" command output with tracefs entry**:
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,relatime,seclabel)
**Error Logged in scx.log file**
Did not find key 'tracefs' in proc_disk_stats map, device name was 'tracefs'.
The diskstats map does not contain a key matching the device named "tracefs", or only 0 columns were found
> tracefs need to be part of ignored FS list.

- source/code/scxsystemlib/process/processinstance.cpp
we updated AIX to latest kernel which already define **extern "C" int getargs**, new this PR to fix the build break for scx. 
@sarojcare can you help to review this PR? thanks.
> disable extern "C" int getargs for latest AIX kernel

- test/code/scxsystemlib/memory/memoryinstance_test.cpp
"lsps -s" command returns used swap space percentage as '0' but calculating
the same based on values from perfstat_memory_total() system call gives a
non-zero value. Changes has done so that if it is AIX platform and if used
swap space value evaluated from output of "lsps -s" command evaluated as
zero compare percentage of used swap space else compare original values.
> On AIX platform, tescase MemoryInstance_Test::testAllMembers, fails if

- source/code/scxsystemlib/os/osinstance.cpp
- test/code/scxsystemlib/os/ospal_test.cpp
testBootTime and testUpTime test cases were failing for HP-UX because boot time read from
/etc/utmpx file was incorrect. It was found that program writing the boot time
in /etc/utmpx for HP-UX is a 32bit process and struct utmpx size was 140 bytes because
time_t tv_sec in 32bit process is a 32bit signed integer. In case of 64bit process time_t
corresponds to 64bit integer so sizeof struct utmpx is 152 bytes due to structure
padding. So when tv_sec was referenced in the struct utmpx then it was referring
to another variable corresponding to a 32bit struct whose value was 0.
This change declares a new struct utmpx32bits for HP-UX which defines tv_sec as 32bit signed
integer. Now sizeof struct utmpx32bits is 140 in 64bit program similar to sizeof
struct utmpx in 32bit program for HP-UX.
> Enabled testBootTime and testUpTime testcases

- source/code/scxsystemlib/common/GetLinuxOS.sh
In SLES version 12 and earlier version information was obtained from file
/etc/SuSE-release but in SLES 15 this file doesn't exists and version information
is obtained from /etc/os-release. When obtaining version info from /etc/os-release
it was like Version=15".0.
This change removes the extra " from the information.
> Fixed version information in SLES 15

- source/code/scxsystemlib/process/processinstance.cpp
On RHEL8 platform process stat fails as it has certain process with name greater than 28 chars.
Ex:
root     20130     2  0 04:39 ?        00:00:00 [kworker/0:2-cgroup_pidlist_destroy]
root     20352     2  0 04:43 ?        00:00:00 [kworker/u128:1-events_unbound]
root     20753     2  0 04:51 ?        00:00:00 [kworker/u128:2-events_unbound]
root     21033     2  0 04:57 ?        00:00:00 [kworker/0:3-events_power_efficient]
root     21035     2  0 04:57 ?        00:00:00 [kworker/u128:0-events_unbound]
It is risk to not check size at can be potential security risk. Hence increased the size.
> On RHEL8, process stat fails as it has process names > 28 chars

- source/code/scxsystemlib/common/GetLinuxOS.sh
Description:
Release file on SuSE platform is 'SuSE-release', but it is coded
as SUSE-release instead. In general, it is not an issue on most
SuSE platforms as release file name is appropriately getting set
using 'ls -F /etc/*-release' command. But on OES platform, a variant
of SuSE platform, the release file name not getting set appropriately when
there are locales defined. Also as linux platform is inherently case-
sensitive it won't be able to select SuSE-release file as well due to
this typo. Hence OES system is eventually get detected as universal
platform instead of SuSE. Hence rectified the typo. Also added provision to
customize release file selection through env variable to handle such
variances.
> OES platform support & Customize release file selection.

- source/code/scxsystemlib/disk/diskdepend.cpp
Below are the few points that would be helpful while reviewing the fix:
1.	This code get executed while sampling the disk stats data. Sampling period is 60 seconds.
2.	This code runs in the context of two threads parallelly.
a.	SCX_DiskDriveStatisticalInformation enumeration query
b.	SCX_FileSystemStatisticalInformation enumeration query
3.	While analyzing core dumps , for few of the data sets, I observed errno is getting set to 9 (bad file descriptor).
4.	Once it is infinite loop, every time it read empty (””) string from file “/proc/diskstats” whereas content of the file is appropriate.
5.	“/proc/diskstats” is a kind of virtual file, when you read data from it, basically you are reading from kernel memory. For better performance and all, it does not have any locking mechanism and all. …
> 100% cpu isssue in omiagent

- source/code/scxsystemlib/common/GetLinuxOS.sh
- test/code/scxsystemlib/common/getlinuxos_test.cpp
- test/code/scxsystemlib/common/platforms/oracle_7/oracle-release
- test/code/scxsystemlib/common/platforms/oracle_7/os-release
- test/code/scxsystemlib/common/platforms/oracle_7/redhat-release
- test/code/scxsystemlib/common/platforms/oracle_7/system-release
@microsoft/omi-devs This PR fixes OSShortName issue for oracle 7, and also adds related unit tests for GetLinuxOS.sh in getlinuxos_test.cpp and the unit tests passed locally.
> Fixes oracle 7 OSShortName issue in GetLinuxOS.sh

- build/Makefile.gcc3
- build/Makefile.pf.AIX
- build/Makefile.pf.SunOS
@microsoft/omi-devs This fixes to support https://github.com/microsoft/SCXcore/pull/170, so the debug symbol folder will be created during generate packages.
> Add -ggdb and -g for pal

- source/code/include/scxsystemlib/statisticaldiskinstance.h
- source/code/include/scxsystemlib/statisticalphysicaldiskinstance.h
- source/code/scxsystemlib/disk/statisticaldiskinstance.cpp
- source/code/scxsystemlib/disk/statisticallogicaldiskenumeration.cpp
- source/code/scxsystemlib/disk/statisticalphysicaldiskenumeration.cpp
- source/code/scxsystemlib/disk/statisticalphysicaldiskinstance.cpp
- test/code/scxsystemlib/disk/diskpal_test.cpp
SCX provider does not handle reserve memory at file system level same as Linux command 'df' handles, which causes difference in  memory related parameters in SCX_FileSystemStatisticalInformation enumeration query. This PR takes care of that issue.
> File system's memory related parameter is different from Linux command DF

- source/code/scxcorelib/util/log/scxlogfilebackend.cpp
Scenario here is: If omiagent has not recevived a single log msg request means file stream has not been initialized at all and subsequent log rotate request will result into crash while attemping to closing uninitialized file stream. 
Most of the time, omiagent running under user 'omi' does not have any log msg and log rotate result into crash this instance.
> Fixing OMIagent crash as part of log rotate

- source/code/include/scxsystemlib/scxkstat.h
- source/code/scxsystemlib/common/scxkstat.cpp
* Update scxkstat.h
* Update scxkstat.cpp
* Update scxkstat.cpp: add locker.
* Update scxkstat.cpp
* Update scxkstat.h
* Update scxkstat.h
* Update scxkstat.cpp
* Update scxkstat.cpp
* Update scxkstat.cpp
* Update scxkstat.cpp
* Update scxkstat.cpp
* Update scxkstat.cpp
* Update scxkstat.h
* Update scxkstat.h
* Update scxkstat.cpp
* Update scxkstat.h
* Update scxkstat.cpp
* Update scxkstat.cpp: add locker.
* Update scxkstat.cpp
* Update scxkstat.h
* Update scxkstat.h
* Update scxkstat.cpp
* Update scxkstat.cpp
* Update scxkstat.cpp
* Update scxkstat.cpp
* Update scxkstat.cpp
* Update scxkstat.cpp
* Update scxkstat.h
* Update scxkstat.h
* Update scxkstat.cpp
* Update scxkstat.cpp
* Update scxkstat.cpp
* Update scxkstat.h
* Update scxkstat.cpp
* Update scxkstat.cpp
* Update scxkstat.h
* …
> Fixes Solaris kstat file leaks. (#23)
